### ISSUE TITLE
Error installing Custom Exporters

### ISSUE THREAD

**Issue by GirasolXimena** [Supernova-Studio/exporters#9]
### Exporter Name

Supernova-Studio/exporters

### Description

When trying to create any custom exporter on `/code/exporters/custom` the following error occurs:

```
    Error thrown: BadRequest: [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "SendPullRequest",
      "PullExporterBundle",
      "ResolveRepositoryBranch"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'SendPullRequest' | 'PullExporterBundle' | 'ResolveRepositoryBranch'"
  }
]

    Code: BadRequest

    Status: 400

    Fields: null

    Request ID: -

    Server time: -

    Network URL: https://api.supernova.io/api/v2/codegen/workspaces/19398/exporters

    Stack: Error: BadRequest: [
  {
    "code": "invalid_union_discriminator",
    "options": [
      "SendPullRequest",
      "PullExporterBundle",
      "ResolveRepositoryBranch"
    ],
    "path": [
      "type"
    ],
    "message": "Invalid discriminator value. Expected 'SendPullRequest' | 'PullExporterBundle' | 'ResolveRepositoryBranch'"
  }
]
    at i.fromNetworkResponse (https://app.supernova.io/_next/static/chunks/9373-b63948a4cbf2f0d6.js:1:211516)
    at iw.handleResponse (https://app.supernova.io/_next/static/chunks/9373-b63948a4cbf2f0d6.js:1:85153)
```
This bug originally happpened while trying to install a custom exporter for my org, but I have validated it occurs with the following URLs:

- https://github.com/zinnia/bloom-token-exporter
- https://github.com/tchief/exporters
-  https://github.com/Supernova-Studio/exporters
- https://github.com/tomalaforge/exporters
- https://github.com/helsenorge/exporters
- https://github.com/OPesicka/apify-supernova-exporter

### Reproducing a bug

1. Go to custom exporters page `/code/exporters/custom`
2. Click `+ New Custom Exporter`
3. Put any valid URL into input:
    - https://github.com/zinnia/bloom-token-exporter
    - https://github.com/tchief/exporters
    -  https://github.com/Supernova-Studio/exporters
    - https://github.com/tomalaforge/exporters
    - https://github.com/helsenorge/exporters
    - https://github.com/OPesicka/apify-supernova-exporter
  4. Error occurs and banner shows on bottom of viewport

### Current Behaviour

Custom exporter cannot be added or validated

### Expected Behaviour

Custom exporter is able to be added and validated

**Comment by honzatmn** [comment]
Hey @GirasolXimena , thank you for this ticket. This is more of a usability issue rather than error while installing it. The URL that you are entering (e.g. https://github.com/Supernova-Studio/exporters/) is not a valid exporter URL. The error message in the product should be improved.

This repository is a monorepo for multiple exporters. So to install a single exporter from this repository, you need to put the URL with the path to the folder. E.g. to install CSS exporter, the correct URL is `https://github.com/Supernova-Studio/exporters/tree/main/exporters/css`. 

Closing this issue. Let me please know if there are some other issues.
